import boolean  # NOQA
import cvrp  # NOQA
import deceptive_step_trap  # NOQA
import deceptive_trap  # NOQA
import function  # NOQA
import leading_ones  # NOQA
import max_sat  # NOQA
import one_max  # NOQA
import pipeline  # NOQA
import rastring  # NOQA
import schwefel  # NOQA
import tsp  # NOQA
